<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.15" />
	<PackageReference Include="FluentValidation" Version="12.1.1" />
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.15">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="MinimalApi.Results" Version="1.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevTask.Core\DevTask.Core.csproj" />
    <ProjectReference Include="..\DevTask.Infrastructure\DevTask.Infrastructure.csproj" />
  </ItemGroup>

</Project>
